### ISSUE TITLE
Need auto effect change program for 8x8x8 LED CUBE

### ISSUE THREAD

**Issue by parasm0802** [VectStudio/LED_CUBE#8]
Can anyone have 8x8x8 LED cube programming file which have automatic effect change? If anyone have please give me. Please help me.
![20190524_125841](https://user-images.githubusercontent.com/50981691/58310249-c5dc1200-7e23-11e9-9aff-d8e595643116.jpg)

**Comment by parasm0802** [comment]
Please help me

**Comment by PARTHKALARIYA** [comment]
Where I get Arduino Program.

**Comment by thexmanxyz** [comment]
@parasm0802 Actually the effects do automatically change and that is also what the code tells us. I don't know why you think they do not. See also [here](https://github.com/VectStudio/LED_CUBE/blob/master/CUBE/CUBE.ino#L86-L87) and [here](https://github.com/VectStudio/LED_CUBE/blob/master/CUBE/CUBE.ino#L98). 

@PARTHKALARIYA The arduino programm is in the sub folder CUBE

**Comment by thexmanxyz** [comment]
@parasm0802 Here I added auto rotation to my [fork branch](https://github.com/thexmanxyz/LED_CUBE/tree/feature/auto_rotate) please also see what [my commit](https://github.com/thexmanxyz/LED_CUBE/commit/7b526c8e8ba2603dd752715f46f248885da9e5c0) changed so that you understand how the auto rotate works and how you can configure it. The [Lines 57-59](https://github.com/thexmanxyz/LED_CUBE/blob/feature/auto_rotate/CUBE/CUBE.ino#L57-L59) are the ones that gonna be interesting for you. It's untested but it should work.

@PARTHKALARIYA The Arduino programm (sketch) is in the sub folder CUBE
